version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: rootthebox
      POSTGRES_USER: rtb
      POSTGRES_PASSWORD: rtb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  webapp:
    build: .
    depends_on:
      - db
      - memcached
    ports:
      - "8888:8888"
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - SQL_DIALECT=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - SQL_DATABASE=rootthebox
      - SQL_USER=rtb
      - SQL_PASSWORD=rtb
volumes:
  postgres-data:
