version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: rootthebox
      POSTGRES_USER: rtb
      POSTGRES_PASSWORD: rtb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  webapp:
    build: .
    depends_on:
      - db
      - memcached
    ports:
      - "8888:8888"
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - SQL_DIALECT=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - SQL_DATABASE=rootthebox
      - SQL_USER=rtb
      - SQL_PASSWORD=rtb

  docker-dind:
    image: docker:24-dind
    privileged: true
    command: ["--host=tcp://0.0.0.0:2375"]
    environment:
      - DOCKER_TLS_CERTDIR=   # desativa TLS dentro do DinD
    volumes:
      - docker-data:/var/lib/docker
    ports:
      - "2375:2375"  # Expose Docker API on port 2375
      - "3000:3000"

  n8n:
    build: ./n8n/
    depends_on:
      - docker-dind
    user: root
    ports:
      - "5678:5678"
    volumes:
      - "~/.n8n:/home/node/.n8n"
    environment:
      - EXECUTIONS_PROCESS=main
      - DOCKER_HOST=tcp://docker-dind:2375
      - N8N_DOCKER_EXEC_BIN=/usr/bin/docker
      - N8N_SECURE_COOKIE=false
  
volumes:
  postgres-data:
  docker-data:
